export {VideoListing} from "./Home/VideoListing";
export {Search} from "./Search/Search";
export {Login} from "./Auth/Login";
export {SignUp} from "./Auth/SignUp";
export {ForgotPassword} from "./Auth/ForgotPassword";
export {PlayList} from "./Playlist/PlayList";
export {LikedVideos} from "./Liked videos/LikedVideos";
export {History} from "./History/History";
export {WatchLater} from "./Watch later/WatchLater";
export {Profile} from "./Profile/Profile";
export {SingleVideo} from "./Single video/SingleVideo";
