export const USER_ACTIONS = {
  INITIAL_PLAYLIST: "INITIAL_PLAYLIST",
  ADD_NEW_PLAYLIST: "ADD_NEW_PLAYLIST",
  DELETE_PLAYLIST: "DELETE_PLAYLIST",
  ADD_VIDEO_TO_PLAYLIST: "ADD_VIDEO_TO_PLAYLIST",
  REMOVE_VIDEO_FROM_PLAYLIST: "REMOVE_VIDEO_FROM_PLAYLIST",
  INITIAL_LIKED_VIDEOS: "INITIAL_LIKED_VIDEOS",
  ADD_TO_LIKED_VIDEOS: "ADD_TO_LIKED_VIDEOS",
  REMOVE_FROM_LIKED_VIDEOS: "REMOVE_FROM_LIKED_VIDEOS",
  INITIAL_WATCH_LATER: "INITIAL_WATCH_LATER",
  ADD_TO_WATCH_LATER: "ADD_TO_WATCH_LATER",
  REMOVE_FROM_WATCH_LATER: "REMOVE_FROM_WATCH_LATER",
};
